# Generated by Django 3.0.5 on 2020-05-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiggler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='quilt',
            field=models.ManyToManyField(related_name='fabrics', to='quiggler.Quilt'),
        ),
    ]
