# Generated by Django 3.0.5 on 2020-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiggler', '0003_auto_20200510_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='quilt',
            field=models.ManyToManyField(blank=True, default=[], related_name='fabrics', to='quiggler.Quilt'),
        ),
    ]
