# Generated by Django 3.0.5 on 2020-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiggler', '0004_auto_20200510_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='quilt',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
